// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	ApiKeyHash string    `json:"api_key_hash"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	SessionID uuid.UUID          `json:"session_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	CreatedAt time.Time          `json:"created_at"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Session struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	UserID        uuid.UUID          `json:"user_id"`
	CreatedAt     time.Time          `json:"created_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	IsAnonymous     bool               `json:"is_anonymous"`
	UserMetadata    []byte             `json:"user_metadata"`
	AppMetadata     []byte             `json:"app_metadata"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
