// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getProjectByAPIKeyHash = `-- name: GetProjectByAPIKeyHash :one
SELECT id, name, api_key_hash, created_at, updated_at
FROM projects
WHERE api_key_hash = $1
`

func (q *Queries) GetProjectByAPIKeyHash(ctx context.Context, apiKeyHash string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByAPIKeyHash, apiKeyHash)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, api_key_hash, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
