// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error
	GetProjectByAPIKeyHash(ctx context.Context, apiKeyHash string) (Project, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	ListUsersByProjectID(ctx context.Context, arg ListUsersByProjectIDParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
