// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, project_id, user_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, user_id, created_at, revoked_at, revoked_reason
`

type CreateSessionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.CreatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, project_id, user_id, created_at, revoked_at, revoked_reason
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const revokeAllRefreshTokensInSession = `-- name: RevokeAllRefreshTokensInSession :exec
UPDATE refresh_tokens SET revoked_at = COALESCE(revoked_at, NOW()) WHERE session_id = $1
`

func (q *Queries) RevokeAllRefreshTokensInSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensInSession, sessionID)
	return err
}

const revokeRefreshTokensByUserSessions = `-- name: RevokeRefreshTokensByUserSessions :exec
UPDATE refresh_tokens SET revoked_at = COALESCE(revoked_at, NOW())
WHERE session_id IN (SELECT s.id FROM sessions s WHERE s.project_id = $1 AND s.user_id = $2)
`

type RevokeRefreshTokensByUserSessionsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeRefreshTokensByUserSessions(ctx context.Context, arg RevokeRefreshTokensByUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensByUserSessions, arg.ProjectID, arg.UserID)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions SET revoked_at = COALESCE(revoked_at, NOW()), revoked_reason = $2 WHERE id = $1
`

type RevokeSessionByIDParams struct {
	ID            uuid.UUID   `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, arg.ID, arg.RevokedReason)
	return err
}

const revokeSessionsByUser = `-- name: RevokeSessionsByUser :exec
UPDATE sessions SET revoked_at = COALESCE(revoked_at, NOW()), revoked_reason = $3 WHERE project_id = $1 AND user_id = $2
`

type RevokeSessionsByUserParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	UserID        uuid.UUID   `json:"user_id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeSessionsByUser(ctx context.Context, arg RevokeSessionsByUserParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsByUser, arg.ProjectID, arg.UserID, arg.RevokedReason)
	return err
}
