// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, project_id, email, password_hash, created_at, updated_at, is_anonymous, user_metadata, app_metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, email, password_hash, created_at, updated_at, email_verified_at, is_anonymous, user_metadata, app_metadata
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"project_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsAnonymous  bool      `json:"is_anonymous"`
	UserMetadata []byte    `json:"user_metadata"`
	AppMetadata  []byte    `json:"app_metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.ProjectID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsAnonymous,
		arg.UserMetadata,
		arg.AppMetadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.IsAnonymous,
		&i.UserMetadata,
		&i.AppMetadata,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, project_id, email, password_hash, created_at, updated_at, email_verified_at, is_anonymous, user_metadata, app_metadata
FROM users
WHERE project_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Email     string    `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.ProjectID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.IsAnonymous,
		&i.UserMetadata,
		&i.AppMetadata,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, project_id, email, password_hash, created_at, updated_at, email_verified_at, is_anonymous, user_metadata, app_metadata
FROM users
WHERE project_id = $1 AND id = $2
`

type GetUserByIDParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ProjectID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.IsAnonymous,
		&i.UserMetadata,
		&i.AppMetadata,
	)
	return i, err
}

const listUsersByProjectID = `-- name: ListUsersByProjectID :many
SELECT id, project_id, email, password_hash, created_at, updated_at, email_verified_at, is_anonymous, user_metadata, app_metadata
FROM users
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByProjectIDParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListUsersByProjectID(ctx context.Context, arg ListUsersByProjectIDParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByProjectID, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailVerifiedAt,
			&i.IsAnonymous,
			&i.UserMetadata,
			&i.AppMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppMetadata = `-- name: UpdateAppMetadata :exec
UPDATE users SET app_metadata = $1, updated_at = NOW() WHERE project_id = $2 AND id = $3
`

type UpdateAppMetadataParams struct {
	AppMetadata []byte    `json:"app_metadata"`
	ProjectID   uuid.UUID `json:"project_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAppMetadata(ctx context.Context, arg UpdateAppMetadataParams) error {
	_, err := q.db.Exec(ctx, updateAppMetadata, arg.AppMetadata, arg.ProjectID, arg.ID)
	return err
}

const updateUserMetadata = `-- name: UpdateUserMetadata :exec
UPDATE users SET user_metadata = $1, updated_at = NOW() WHERE project_id = $2 AND id = $3
`

type UpdateUserMetadataParams struct {
	UserMetadata []byte    `json:"user_metadata"`
	ProjectID    uuid.UUID `json:"project_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) error {
	_, err := q.db.Exec(ctx, updateUserMetadata, arg.UserMetadata, arg.ProjectID, arg.ID)
	return err
}
