// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeUser = `-- name: AnonymizeUser :exec
UPDATE users SET
  email = 'deleted-' || id::text || '@anonymized.local',
  password_hash = '',
  user_metadata = '{}',
  app_metadata = '{}',
  updated_at = NOW(),
  deleted_at = COALESCE(deleted_at, NOW())
WHERE project_id = $1 AND id = $2
`

type AnonymizeUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) AnonymizeUser(ctx context.Context, arg AnonymizeUserParams) error {
	_, err := q.db.Exec(ctx, anonymizeUser, arg.ProjectID, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, project_id, email, password_hash, created_at, updated_at, is_anonymous, user_metadata, app_metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, email, password_hash, created_at, updated_at, email_verified_at, is_anonymous, user_metadata, app_metadata, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"project_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsAnonymous  bool      `json:"is_anonymous"`
	UserMetadata []byte    `json:"user_metadata"`
	AppMetadata  []byte    `json:"app_metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.ProjectID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsAnonymous,
		arg.UserMetadata,
		arg.AppMetadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.IsAnonymous,
		&i.UserMetadata,
		&i.AppMetadata,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, project_id, email, password_hash, created_at, updated_at, email_verified_at, is_anonymous, user_metadata, app_metadata, deleted_at
FROM users
WHERE project_id = $1 AND email = $2 AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Email     string    `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.ProjectID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.IsAnonymous,
		&i.UserMetadata,
		&i.AppMetadata,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, project_id, email, password_hash, created_at, updated_at, email_verified_at, is_anonymous, user_metadata, app_metadata, deleted_at
FROM users
WHERE project_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ProjectID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.IsAnonymous,
		&i.UserMetadata,
		&i.AppMetadata,
		&i.DeletedAt,
	)
	return i, err
}

const getUsersDeletedBefore = `-- name: GetUsersDeletedBefore :many
SELECT id, project_id FROM users WHERE deleted_at IS NOT NULL AND deleted_at <= $1
`

type GetUsersDeletedBeforeRow struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetUsersDeletedBefore(ctx context.Context, deletedAt pgtype.Timestamptz) ([]GetUsersDeletedBeforeRow, error) {
	rows, err := q.db.Query(ctx, getUsersDeletedBefore, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersDeletedBeforeRow
	for rows.Next() {
		var i GetUsersDeletedBeforeRow
		if err := rows.Scan(&i.ID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users WHERE project_id = $1 AND id = $2 AND deleted_at IS NOT NULL
`

type HardDeleteUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) HardDeleteUser(ctx context.Context, arg HardDeleteUserParams) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, arg.ProjectID, arg.ID)
	return err
}

const listUsersByProjectID = `-- name: ListUsersByProjectID :many
SELECT id, project_id, email, password_hash, created_at, updated_at, email_verified_at, is_anonymous, user_metadata, app_metadata, deleted_at
FROM users
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByProjectIDParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListUsersByProjectID(ctx context.Context, arg ListUsersByProjectIDParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByProjectID, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailVerifiedAt,
			&i.IsAnonymous,
			&i.UserMetadata,
			&i.AppMetadata,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = COALESCE(deleted_at, NOW()) WHERE project_id = $1 AND id = $2
`

type SoftDeleteUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.ProjectID, arg.ID)
	return err
}

const updateAppMetadata = `-- name: UpdateAppMetadata :exec
UPDATE users SET app_metadata = $1, updated_at = NOW() WHERE project_id = $2 AND id = $3 AND deleted_at IS NULL
`

type UpdateAppMetadataParams struct {
	AppMetadata []byte    `json:"app_metadata"`
	ProjectID   uuid.UUID `json:"project_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAppMetadata(ctx context.Context, arg UpdateAppMetadataParams) error {
	_, err := q.db.Exec(ctx, updateAppMetadata, arg.AppMetadata, arg.ProjectID, arg.ID)
	return err
}

const updateUserMetadata = `-- name: UpdateUserMetadata :exec
UPDATE users SET user_metadata = $1, updated_at = NOW() WHERE project_id = $2 AND id = $3 AND deleted_at IS NULL
`

type UpdateUserMetadataParams struct {
	UserMetadata []byte    `json:"user_metadata"`
	ProjectID    uuid.UUID `json:"project_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) error {
	_, err := q.db.Exec(ctx, updateUserMetadata, arg.UserMetadata, arg.ProjectID, arg.ID)
	return err
}
